export const Types = {
  FETCH_POSTS: "FETCH_POSTS",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_FAILED: "FETCH_POSTS_FAILED",

  DELETE_POST: "DELETE_POST",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILED: "DELETE_POST_FAILED",

  EDIT_POST: "EDIT_POST",
  EDIT_POST_SUCCESS: "EDIT_POST_SUCCESS",
  EDIT_POST_FAILED: "EDIT_POST_FAILED",

  ADD_POST: "ADD_POST",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_FAILED: "ADD_POST_FAILED"
};
